### ISSUE TITLE
Error "0" from server:

### ISSUE THREAD

**Issue by fullyconnected** [socrata/soda-php#11]
Hello,

Are you able to tell me what's wrong with my code? I keep getting the error "0" from server.

Here's my code shown below, which is from your example code...

Thanks in advance.

<?php
  require_once("socrata.php");

  $view_uid = "qiz3-axqb";
  $root_url = "https://data.cityofnewyork.us";
  $app_token = "bjp8KrRvAPtuf809u1UXnI0Z8";

  $response = NULL;

  $incident_zip = array_get("incident_zip",$_POST);

  if($incident_zip != NULL) {
    // Create a new unauthenticated client
    $socrata = new Socrata($root_url, $app_token);

    $params = array("\$where" => "starts_with(incident_zip, '11207')");

    $response = $socrata->get("/resource/$view_uid.json", $params);
  }
?>
<html>
  

    <?php if($response == NULL) { ?>
      <form action="311.php" method="POST">
      
        <label for="incident_zip">Zip Code</label>
        <input type="text" name="incident_zip" size="10" value="11207"/><br/>

        <input type="submit" value="Submit"/>
      </form>
    <?php } else { ?>
      <h2>Results</h2>

      <?# Create a table for our actual data ?>
      <table border="1">
        <tr>
          <th>Agency</th>
          <th>Complaint Type</th>
        </tr>
        <?# Print rows ?>
        <?php foreach($response as $row) { ?>
          <tr>
            <td><?= $row["agency"] ?></td>
            <td><?= $row["complaint_type"] ?></td>
          </tr>
        <?php } ?>
      </table>

      <h3>Raw Response</h3>
      <pre><?= var_dump($response) ?></pre>
    <?php } ?>
  </body>
</html>

**Comment by allejo** [comment]
The dataset you're trying to access doesn't have a `incident_zip` column.

To achieve your goal, try building a query like so:
```
http://data.cityofnewyork.us/resource/qiz3-axqb.json?$where=zip_code='11207'
```

**Comment by fullyconnected** [comment]
@allejo  Thank you very much... The names on the dataset were different from the .json response

**Comment by fullyconnected** [comment]
@allejo    How can I add two parameters to this assoc array? For example, I wanted to add a parameter which would have the date ('created_date') appear in descending order. According to the documentation I should use $order= created_date DESC, but unsure how to add to this parameter. The dataset is sorting in ASC order, I just need to reverse it. 


  $incident_zip = array_get("incident_zip",$_POST);

 $params = array("\$where" => "starts_with(incident_zip, '$incident_zip')");


Here's the code:

require_once("socrata.php");



  $view_uid = "erm2-nwe9";
  $root_url = "http://data.cityofnewyork.us/";
  $app_token = "fuIbKtpMtlhma6piFMI18sz43";

 
  $response = NULL;

  $incident_zip = array_get("incident_zip",$_POST);

  if($incident_zip != NULL) {
    // Create a new unauthenticated client
    $socrata = new Socrata($root_url, $app_token);

    $params = array("\$where" => "starts_with(incident_zip, '$incident_zip')");



    $response = $socrata->get("/resource/$view_uid.json",$params);
  }
?>
<html>
  <head>
    <title> 311 Service Requests</title>
  </head>
  <body>
    <h1>311 Service Requests</h1>

    <?php if($response == NULL) { ?>
      <form action="311.php" method="POST">
      
        <label for="incident_zip">Zip Code</label>
        <input type="text" name="incident_zip" size="5" value=""/><br/>

        <input type="submit" value="Submit"/>
      </form>
    <?php } else { ?>
     

      <?# Create a table for our actual data ?>
      <table border="1" width="400" >
        <tr>
          <th>Date</th>
          <th>Zip</th>
          <th>Complaint Type</th>
          <th>Street Name</th>
          <th>City</th>
          <th>Agency</th>
          <th>Resolution</th>
          <th>Desc</th>
          <th>Address</th>
          <th>Location Type</th>
          </tr>
        <?# Print rows ?>
        <?php foreach($response as $row) { ?>
          <tr>
            <td><?= $row["created_date"] ?></td>
            <td><?= $row["incident_zip"] ?></td>
            <td><?= $row["complaint_type"] ?></td>
            <td><?= $row["street_name"] ?></td>
            <td><?= $row["city"] ?></td> 
            <td><?= $row["agency_name"] ?></td> 
            <td><?= $row["resolution_description"] ?></td>
            <td><?= $row["descriptor"] ?></td> 
            <td><?= $row["incident_address"] ?></td> 
            <td><?= $row["location_type"] ?></td> 
            </tr>
        <?php } ?>
      </table>

      
     <?php } ?>

  </body>
</html>

**Comment by allejo** [comment]
Separate it with a comma. Something like this would do:

```php
$params = array(
              "\$where" => "starts_with(incident_zip, '$incident_zip')",
              "\$order" => "<something>"
          );
```

**Comment by fullyconnected** [comment]
@allejo Thank you very much.
