### ISSUE TITLE
Support OAuth2 

### ISSUE THREAD

**Issue by manrajsingh** [socrata/soda-php#13]
Please add the support of authenticating with Socrata with OAuth2 method.

**Comment by allejo** [comment]
You could take a look at [PhpSoda](https://github.com/allejo/PhpSoda) which has [`setOAuth2Token()`](https://github.com/allejo/PhpSoda/blob/master/src/SodaClient.php#L229). If you could test to see if works that'd be great, if not I'd be more than happy to fix it.
