### ISSUE TITLE
at submit getting this error

### ISSUE THREAD

**Issue by amirul1000** [socrata/soda-php#15]
cURL error: SSL certificate problem: unable to get local issuer certificate

**Comment by allejo** [comment]
What version of PHP are you running?

**Comment by chrismetcalf** [comment]
@amirul1000 Also, what domain are you accessing? It's likely that your system's root SSL certificates are old and you need to update them. Doing a system upgrade or at least an upgrade of PHP and OpenSSL should probably help.

**Comment by amirul1000** [comment]
curl_setopt($handle, CURLOPT_SSL_VERIFYPEER, false);

finally i fixed in this way

tnx everybody

**Comment by chrismetcalf** [comment]
That'll work, but be careful as it does disable SSL verification and leads
you vulnerable to man in the middle attacks.

-- 
Chris Metcalf
