### ISSUE TITLE
Don't die() on me

### ISSUE THREAD

**Issue by sanderdekroon** [socrata/soda-php#23]
Please remove the echo and die() statements from your library. It makes no sense whatsoever to let PHP die() is there's an unexpected result.

Instead, return an array with an error/error code or throw an catchable exception.

A simple solution would be:
```php
if($code != "200") {
      return array('status' => false, 'statusCode' => $code);
}
```

That way we can simply check the response from the function with `isset($response['status'])` and retrieve the status code if we want to.

Alternatively you could implement a custom Exception and throw that instead.

**Comment by allejo** [comment]
Are you using the latest master? This was fixed in 208d16b013ea58b59655df130be4e0cbc020ab62

**Comment by sanderdekroon** [comment]
Huh, that's odd. I downloaded the library last week via composer, but apparently not the latest master.

**Comment by chrismetcalf** [comment]
@sanderdekroon, @allejo Did I not update something properly in Composer? I replaced the `die()`s with exceptions, but it wouldn't surprise me if there wasn't some other packaging detail I missed.

**Comment by allejo** [comment]
Composer uses tags for stable releases by default so unless someone is using `dev-master` explicitly in their composer.json, they'll be getting the last tag which doesn't include your changes.

**Comment by chrismetcalf** [comment]
@allejo GitHub release tags? So if I cut a new tag in GitHub that'll work?

**Comment by allejo** [comment]
Yea, a newer tag will allow users to pull that as the current "stable" release instead of having users always pull the latest master (which could possibly be under development). The [latest "stable"](https://packagist.org/packages/socrata/soda-php) is currently 1.0.5.

**Comment by chrismetcalf** [comment]
@allejo Like this? https://github.com/socrata/soda-php/releases/tag/v1.1.0

@sanderdekroon Let me know if the 1.1.0 release works for you now.

**Comment by allejo** [comment]
@chrismetcalf that should do it 👍 

Just target `1.1.x` in your composer file and run `composer update`.

**Comment by chrismetcalf** [comment]
Cool, I like how that works! Thanks for your help as usual, @allejo! 🍻
