### ISSUE TITLE
Merge develop into master

### ISSUE THREAD

**Issue by texdc** [socrata/soda-php#9]
I know I initially requested it, but I think it's overkill to have the `develop` branch.  It's really only necessary for projects with lots of changes.  Since I renamed the class and reorganized things for `PSR-4` autoloading, I wanted to get the changes reviewed before releasing.  I would like for it to be tested in a staging environment before tagging a release, but `master` should be sufficient for that.

**Comment by chrismetcalf** [comment]
Awesome, thanks, and sorry for the delay!
